name: log_engine
description: "Logger for Flutter Apps"


version: 2.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^8.13.2
  json_annotation: ^4.9.0
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.1.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_serializable: ^6.3.1


flutter:
  uses-material-design: true
